version: "2"
services: 
  # Nginx 1.11.10: https://hub.docker.com/_/nginx/
  web:
    image: nginx:1.11.10
    ports:
      # 将主机的 8888 端口映射到容器的 80 端口
      - 8888:80
    depends_on:
      - php
    # 同 php 一起共享 ./apps 目录
    volumes_from:
      - php
    # 创建一个数据卷，由 ./images/nginx/config => /etc/nginx/conf.d
    volumes:
      - ./images/nginx/config:/etc/nginx/conf.d:ro

  # PHP 7.1-fpm: https://hub.docker.com/_/php/
  php:
    build: 
      context: ./docker/php
      dockerfile: DockerFile
    volumes: 
      - ./apps:/mnt/apps

  # MySQL 5.7: https://hub.docker.com/_/mysql/
  database: 
    image: mysql:5.7
    # 配置一些环境变量，具体的环境变量细节可以访问上面的网址查看
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "nine"
      MYSQL_PASSWORD: "nine"
    volumes:
      - ./database:/var/lib/mysql